name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4', '8.5']
      fail-fast: false
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: sqlite3, mbstring

      - name: Check PHP Version
        run: php -v

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run tests
        run: vendor/bin/tester tests -C
